export const CONTROL_PLANE_ROUTES = {
  health: '/api/control/health',
  publicStats: '/api/control/public-stats',
  dashboardMaintenance: '/api/control/dashboard/maintenance',
  dashboardUpdateAnnouncements: '/api/control/dashboard/update-announcements',
  dashboardDeveloperAnalytics: '/api/control/dashboard/developer-analytics',
  dashboardDeveloperGuildInventory: '/api/control/dashboard/developer-guild-inventory',
  updateAnnouncements: '/api/control/updates/announce',
  guilds: '/api/control/guilds',
  dashboardGuilds: '/api/control/dashboard/guilds',
  guildConfig: (guildId: string) => `/api/control/guilds/${guildId}/config`,
  guildPlugins: (guildId: string) => `/api/control/guilds/${guildId}/plugins`,
  guildPluginDiagnostics: (guildId: string) => `/api/control/guilds/${guildId}/diagnostics`,
  guildAntiPing: (guildId: string) => `/api/control/guilds/${guildId}/antiping`,
  guildStarboard: (guildId: string) => `/api/control/guilds/${guildId}/starboard`,
  guildLogging: (guildId: string) => `/api/control/guilds/${guildId}/logging`,
  guildAutomod: (guildId: string) => `/api/control/guilds/${guildId}/automod`,
  guildHoneypot: (guildId: string) => `/api/control/guilds/${guildId}/honeypot`,
  guildAutomodRaidMode: (guildId: string) => `/api/control/guilds/${guildId}/automod/raid-mode`,
  guildProgression: (guildId: string) => `/api/control/guilds/${guildId}/progression`,
  guildStatistics: (guildId: string) => `/api/control/guilds/${guildId}/statistics`,
  guildTickets: (guildId: string) => `/api/control/guilds/${guildId}/tickets`,
  guildTicketQueue: (guildId: string) => `/api/control/guilds/${guildId}/tickets/queue`,
  guildTicketAnalytics: (guildId: string) => `/api/control/guilds/${guildId}/tickets/analytics`,
  guildTicketsPanelMessage: (guildId: string) =>
    `/api/control/guilds/${guildId}/tickets/panel-message`,
  guildEmbeds: (guildId: string) => `/api/control/guilds/${guildId}/embeds`,
  guildWelcome: (guildId: string) => `/api/control/guilds/${guildId}/welcome`,
  guildEmbedsSend: (guildId: string) => `/api/control/guilds/${guildId}/embeds/send`,
  transcripts: (guildId: string) => `/api/control/guilds/${guildId}/transcripts`,
  transcript: (transcriptId: string) => `/api/control/transcripts/${transcriptId}`,
  transcriptMessages: (transcriptId: string) => `/api/control/transcripts/${transcriptId}/messages`,
} as const;
